# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import purchase_pb2 as purchase__pb2


class PurchaseStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.purchase = channel.unary_unary(
        '/freo.me.purchase.Purchase/purchase',
        request_serializer=purchase__pb2.PurchaseRequest.SerializeToString,
        response_deserializer=purchase__pb2.PurchaseReply.FromString,
        )


class PurchaseServicer(object):
  """The greeting service definition.
  """

  def purchase(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PurchaseServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'purchase': grpc.unary_unary_rpc_method_handler(
          servicer.purchase,
          request_deserializer=purchase__pb2.PurchaseRequest.FromString,
          response_serializer=purchase__pb2.PurchaseReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'freo.me.purchase.Purchase', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
