# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: purchase.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='purchase.proto',
  package='freo.me.purchase',
  syntax='proto3',
  serialized_pb=_b('\n\x0epurchase.proto\x12\x10\x66reo.me.purchase\"\x9f\x01\n\x0fPurchaseRequest\x12\x10\n\x08poNumber\x18\x01 \x01(\t\x12\x10\n\x08lineItem\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12$\n\x04\x64\x61te\x18\x04 \x01(\x0b\x32\x16.freo.me.purchase.Date\x12\x16\n\x0e\x63ustomerNumber\x18\x05 \x01(\t\x12\x18\n\x10paymentReference\x18\x06 \x01(\t\"0\n\x04\x44\x61te\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\"4\n\rPurchaseReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nreturncode\x18\x02 \x01(\x05\x32\\\n\x08Purchase\x12P\n\x08purchase\x12!.freo.me.purchase.PurchaseRequest\x1a\x1f.freo.me.purchase.PurchaseReply\"\x00\x62\x06proto3')
)




_PURCHASEREQUEST = _descriptor.Descriptor(
  name='PurchaseRequest',
  full_name='freo.me.purchase.PurchaseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='poNumber', full_name='freo.me.purchase.PurchaseRequest.poNumber', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lineItem', full_name='freo.me.purchase.PurchaseRequest.lineItem', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='freo.me.purchase.PurchaseRequest.quantity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='freo.me.purchase.PurchaseRequest.date', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='customerNumber', full_name='freo.me.purchase.PurchaseRequest.customerNumber', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paymentReference', full_name='freo.me.purchase.PurchaseRequest.paymentReference', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=196,
)


_DATE = _descriptor.Descriptor(
  name='Date',
  full_name='freo.me.purchase.Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='freo.me.purchase.Date.year', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='month', full_name='freo.me.purchase.Date.month', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='day', full_name='freo.me.purchase.Date.day', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=246,
)


_PURCHASEREPLY = _descriptor.Descriptor(
  name='PurchaseReply',
  full_name='freo.me.purchase.PurchaseReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='freo.me.purchase.PurchaseReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='returncode', full_name='freo.me.purchase.PurchaseReply.returncode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=300,
)

_PURCHASEREQUEST.fields_by_name['date'].message_type = _DATE
DESCRIPTOR.message_types_by_name['PurchaseRequest'] = _PURCHASEREQUEST
DESCRIPTOR.message_types_by_name['Date'] = _DATE
DESCRIPTOR.message_types_by_name['PurchaseReply'] = _PURCHASEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PurchaseRequest = _reflection.GeneratedProtocolMessageType('PurchaseRequest', (_message.Message,), dict(
  DESCRIPTOR = _PURCHASEREQUEST,
  __module__ = 'purchase_pb2'
  # @@protoc_insertion_point(class_scope:freo.me.purchase.PurchaseRequest)
  ))
_sym_db.RegisterMessage(PurchaseRequest)

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), dict(
  DESCRIPTOR = _DATE,
  __module__ = 'purchase_pb2'
  # @@protoc_insertion_point(class_scope:freo.me.purchase.Date)
  ))
_sym_db.RegisterMessage(Date)

PurchaseReply = _reflection.GeneratedProtocolMessageType('PurchaseReply', (_message.Message,), dict(
  DESCRIPTOR = _PURCHASEREPLY,
  __module__ = 'purchase_pb2'
  # @@protoc_insertion_point(class_scope:freo.me.purchase.PurchaseReply)
  ))
_sym_db.RegisterMessage(PurchaseReply)



_PURCHASE = _descriptor.ServiceDescriptor(
  name='Purchase',
  full_name='freo.me.purchase.Purchase',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=302,
  serialized_end=394,
  methods=[
  _descriptor.MethodDescriptor(
    name='purchase',
    full_name='freo.me.purchase.Purchase.purchase',
    index=0,
    containing_service=None,
    input_type=_PURCHASEREQUEST,
    output_type=_PURCHASEREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PURCHASE)

DESCRIPTOR.services_by_name['Purchase'] = _PURCHASE

# @@protoc_insertion_point(module_scope)
